import os
import time
import pickle
from dotenv import load_dotenv
from google import genai
from google.genai import types
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
import googleapiclient.discovery
from googleapiclient.http import MediaFileUpload

# --- 1. CONFIGURATION & SECRETS ---
load_dotenv()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
CLIENT_SECRETS_FILE = "client_secrets.json"
TOKEN_FILE = "token.json"
YOUTUBE_SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

def get_authenticated_service():
    """Bypasses 2FA by using a saved token.json file."""
    creds = None
    if os.path.exists(TOKEN_FILE):
        with open(TOKEN_FILE, 'rb') as token:
            creds = pickle.load(token)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(CLIENT_SECRETS_FILE, YOUTUBE_SCOPES)
            creds = flow.run_local_server(port=0)
        with open(TOKEN_FILE, 'wb') as token:
            pickle.dump(creds, token)
    return googleapiclient.discovery.build("youtube", "v3", credentials=creds)

def generate_random_prompt():
    """Uses Gemini Text (high quota) to invent a weird video idea."""
    print("🧠 Brainstorming a new idea...")
    try:
        client = genai.Client(api_key=GEMINI_API_KEY)
        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents="Write a 1-sentence cinematic prompt for a weird, surreal, or funny AI video. No robots making sandwiches—be more creative."
        )
        return response.text.strip()
    except Exception as e:
        print(f"⚠️ Brainstorming failed, using fallback prompt. Error: {e}")
        return "A surreal chrome creature wandering through a neon digital wasteland"

def generate_video_with_veo(prompt):
    """Uses Veo 3.1 to turn the prompt into a video file."""
    if not GEMINI_API_KEY:
        print("❌ ERROR: No API Key found in .env file!")
        return None

    client = genai.Client(api_key=GEMINI_API_KEY)
    print(f"🎬 Veo 3.1 is imagining: {prompt}")
    
    try:
        operation = client.models.generate_videos(
            model="veo-3.1-generate-preview",
            prompt=prompt,
            config=types.GenerateVideosConfig(aspect_ratio="16:9", duration_seconds=8)
        )

        while not operation.done:
            print("⏳ Rendering... (Check back in 1-2 mins)")
            time.sleep(20)
            operation = client.operations.get(operation)

        timestamp = time.strftime("%Y%m%d-%H%M%S")
        filename = f"trash_{timestamp}.mp4"
        
        video = operation.result.generated_videos[0]
        client.files.download(file=video.video)
        video.video.save(filename)
        print(f"✅ Saved: {filename}")
        return filename

    except Exception as e:
        if "429" in str(e):
            print("\n❌ QUOTA EXHAUSTED: Try again after midnight Pacific Time.")
        else:
            print(f"\n❌ ERROR: {e}")
        return None

def upload_to_youtube(file_path, title):
    """Uploads the video to your channel as 'Private'."""
    youtube = get_authenticated_service()
    print(f"🚀 Uploading to YouTube: {title}")
    
    body = {
        'snippet': {
            'title': title,
            'description': 'Generated by the Endless Trash Pipeline',
            'categoryId': '22'
        },
        'status': {'privacyStatus': 'private'}
    }

    request = youtube.videos().insert(
        part="snippet,status",
        body=body,
        media_body=MediaFileUpload(file_path, chunksize=-1, resumable=True)
    )
    response = request.execute()
    print(f"📺 SUCCESS! Video ID: {response['id']}")

# --- MAIN EXECUTION ---
if __name__ == "__main__":
    print(f"\n--- STARTING PIPELINE: {time.strftime('%H:%M:%S')} ---")
    
    # Step 1: Get a random idea
    prompt = generate_random_prompt()
    
    # Step 2: Try to make the video
    video_file = generate_video_with_veo(prompt)
    
    # Step 3: Upload if it worked
    if video_file:
        upload_to_youtube(video_file, f"Endless Trash: {prompt[:50]}...")
    else:
        print("⏭️ Pipeline stopped. No video to upload.")